import Header from "@/components/Header";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PromptInput from "@/components/PromptInput";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        {/* Header */}
        <Header />

        {/* Prompt input  */}
        <PromptInput />

        {children}
      </body>
    </html>
  );
}
